### PR TITLE
Problem25

### PR DESCRIPTION
**Pull request by oli-obk**
find the first fibonacci number with more than 1000 digits

### CODE REVIEW

**Comment by 5nyper** [comment]
I need confirmation that the result of this code is the right answer to accept PR.

**Comment by oli-obk** [comment]
(i, length, fib) = (4782, 1000, 1070066266382758936764980584457396885083683896632151665013235203375314520604694040621889147582489792657804694888177591957484336466672569959512996030461262748092482
186144069433051234774442750273781753087579391666192149259186759553966422837148943113074699503439547001985432609723067290192870526447243726117715821825548491120525013201478612965931381792235559657
452039506137551467837543229119602129934048260706175397706847068202895486902666185435124521900369480641357447470911707619766945691070098024393439617474103736912503231365532164773697023167755051595
173518460579954919410967778373229665796581646513903488154256310184224190259846088000110186255550245493937113651657039447629584714548523425950428582425306083544435428212611008992863795048006894330
309773217834864543113205765659868456288616808718693835297350643986297640660000723562917905207051164077614812491885830945940566688339109350944456576357666151619317753792891661581327159616877487983
821820492520348473874384736771934512787029218636250627816)
Previous fib number length: 999

**Comment by oli-obk** [comment]
the previous fib number has 999 digits, the new one is the first with 1k.

the i fits with the one from the problem

**Comment by 5nyper** [comment]
I swear this is exactly what I did, oh well, PR accepted.

**Pull request merged**
